# Generated by Django 3.2.5 on 2021-07-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210718_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Paypal'), (2, 'Master'), (3, 'Visa')], default=1),
            preserve_default=False,
        ),
    ]
