# Generated by Django 3.2.5 on 2021-07-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Paypal'), (2, 'Master'), (3, 'Visa')], null=True),
        ),
    ]
